config/routes.rb
Lms::Application.routes.draw do

  resources :users do
    collection do 
      post :import_for_creating
      post :import_for_involving
    end
		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
		end
    resources :notifications, only: [:index]  
		resources :groups do
      resources :courses, only: [:index, :create, :update, :destroy] do
        resources :evaluations, only: [:create, :update, :destroy] do
          resources :marks, only: [:index, :update]
        end
      end 
			resources :tasks, only: [:create, :edit, :update, :index, :destroy]
		  resources :microposts, only: [:create]
  		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
  			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
  		end
      resources :etherpads, only: [:create, :destroy, :show]
		end
	end	

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'
  
  ############
  ### user ###
  ############
  
  get '/signedup', to: 'users#signedup', as: 'signedup'
  put '/user/update', to: 'users#update', as: 'user_update'
  
  #############
  ### group ###
  #############
  
  put '/user/group/rename', to: 'groups#update', as: 'rename_group'
  delete '/user/group/destroy', to: 'groups#destroy', as: 'destroy_group'
  get 'user/group/autocomplete_user', to: 'groups#autocomplete_user_name', as: 'autocomplete_user_name'
  
  ##################
  ### invitation ###
  ##################
  
  put '/user/group/send_invitation', to: 'groups#send_invitation', as: 'send_invitation'
  get '/user/group/autocomplete', to: 'groups#autocomplete', as: 'autocomplete'
  
  #
  
  get '/confirmation',  to: 'sessions#create'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/signup',  to: 'signup#new'
  get '/signup/team',  to: 'signup#team', as: 'team_setup'


  get '/users/:user_id/allgroups', to: 'groups#show_all', as: 'allgroups'
  post '/user/:user_id/group/:group_id', to: 'groups#join_group', as: 'joingroup'
  delete '/user/:user_id/group/:group_id', to: 'groups#leave_group', as: 'leavegroup'
  
  put '/users/:user_id/viewparams', to: 'viewparams#update', as: 'params'
  
  get '/users/:user_id/groups/:group_id/courses/:course_id/evaluations/:evaluation_id/marks/average', to: 'evaluations#get_average', as: 'get_average_evaluation'
  get '/users/:user_id/groups/:group_id/courses/:course_id/average', to: 'courses#get_average', as: 'get_average_course'
  
  ###############
  ### roadmap ###
  ###############
  
  get '/roadmap',  to: 'sessions#roadmap', as: 'roadmap'
  
  ###########
  ### box ###
  ###########
  
  # oauth
  
  get '/user/send_oauth', to: 'oauths#send_oauth', as: 'send_oauth'
  get '/user/receive_oauth', to: 'oauths#receive_oauth', as: 'receive_oauth'
  get '/user/refresh_token', to: 'oauths#refresh_token', as: 'refresh_token'  
  
  # perso #

  get '/user/documents', to: 'simpledocuments#index', as: 'get_user_documents'
  get '/user/file/download', to: 'simpledocuments#download', as: 'download_user_file'
  get '/user/document/show', to: 'simpledocuments#show', as: 'show_user_file'
  get '/user/document/arianewire', to: 'simpledocuments#ariane_wire', as: 'get_document_ariane_wire'
  get '/user/document/previousfolder', to: 'simpledocuments#previous_folder', as: 'get_user_previous_folder'
  
  post '/user/file/upload', to: 'simpledocuments#upload_file', as: 'upload_user_file'
  post 'user/create_folder', to: 'simpledocuments#create_folder', as: 'create_user_folder'
  post 'user/file/create_shared_link', to: 'simpledocuments#create_shared_link', as: 'create_shared_link'
  
  put '/user/file/rename', to: 'simpledocuments#update', as: 'rename_user_file'
  put '/user/folder/rename', to: 'simpledocuments#update', as: 'rename_user_folder'
  
  put '/user/file/move', to: 'simpledocuments#move_file', as: 'move_user_file'
  put '/user/folder/move', to: 'simpledocuments#move_folder', as: 'move_user_folder'
  
  delete '/user/document/delete', to: 'simpledocuments#destroy', as: 'delete_user_document' 
  
  # group #
  
  get '/user/group/documents', to: 'groupdocuments#read_folder', as: 'get_group_documents'
  get '/user/group/document/download', to: 'groupdocuments#download_file', as: 'download_group_file'
  get '/user/group/document/read', to: 'groupdocuments#read_file', as: 'read_group_file'
  
  post '/user/group/file/create', to: 'groupdocuments#create_file', as: 'create_group_file'
  post '/user/group/folder/create', to: 'groupdocuments#create_folder', as: 'create_group_folder'
  post '/user/group/file/create_shared_link', to: 'groupdocuments#create_shared_link', as: 'create_group_shared_link'
  
  put '/user/group/file/move', to: 'groupdocuments#move_file', as: 'move_group_file'
  put '/user/group/folder/move', to: 'groupdocuments#move_folder', as: 'move_group_folder'
  put '/user/group/file/rename', to: 'groupdocuments#rename_file', as: 'rename_group_file'
  put '/user/group/folder/rename', to: 'groupdocuments#rename_folder', as: 'rename_group_folder'
  put '/user/group/folder/transfer', to: 'groupdocuments#transfer_folder', as: 'transfer_group_folder'
  put '/user/group/file/transfer', to: 'groupdocuments#transfer_file', as: 'transfer_group_file'

  delete '/user/group/document/file/delete', to: 'groupdocuments#destroy_file', as: 'delete_group_file'
  delete '/user/group/document/folder/delete', to: 'groupdocuments#destroy_folder', as: 'delete_group_folder'
  
  ############
  ### chat ###
  ############
  
  get '/user/group/chats', to: 'groupchats#index', as: 'get_group_chats'
  post '/user/group/chat/message/create', to: 'messages#create', as: 'create_message'
  post '/user/group/chat/chat/create', to: 'groupchats#create', as: 'create_chat'
  
  ###############
  ### firepad ###
  ###############
  
  get '/user/group/document/firepad/read', to: 'firepads#read', as: 'read_firepad'
  post '/user/group/document/firepad/create', to: 'firepads#create', as: 'create_firepad'
  
  put '/user/group/document/firepad/rename', to: 'firepads#rename', as: 'rename_firepad'
  put '/user/group/document/firepad/move', to: 'firepads#move', as: 'move_firepad'
  put '/user/group/document/firepad/transfer', to: 'firepads#transfer', as: 'transfer_firepad'
  
  delete '/user/group/document/firepad/destroy', to: 'firepads#destroy', as: 'destroy_firepad'
  
end

app/views/popup/_popup.html.erb
<div id="background-grey"></div>

<%= render 'popup/popup_all_groups' %>
<%= render 'popup/popup_config' %>
<%= render 'popup/popup_new_group' %>
<%= render 'popup/popup_signup' %>
<%= render 'popup/popup_transfer' %>

app/views/popup/_popup_all_groups.html.erb
<div id="slide-all-groups" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <span class="header-title">Select a group</span>
      <div class="fa fa-close" id="close-all-groups"></div>
    </div>
    <div class="slide-body" id="body-all-groups">
      <div class="wrapper-group-list" id="all-groups-wrapper">
        <div class="group-list group-list-all-groups">
          <% current_groups.each do |group| %>
            <%= link_to get_group_documents_path(group_id: group.id, parent_id: 100), class: "list-element" do %>
              <i class="fa fa-group"></i>
              <span class="list-element-name" group_id="<%= group.id %>">
                <%= group.name %>
              </span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="slide-footer">
      <input type="submit" value="Select" class="submit-default validate-default" id="all-groups-submit">
    </div>
  </div>
</div>

app/views/popup/_popup_config.html.erb
<div id="slide-group-config" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <span class="header-title">Configuration</span>
      <div class="fa fa-close" id="close-group-config"></div>
    </div>
    <div class="slide-body">

      

      <div class="config-wrapper" id="config-rename">
        <div class="title-popup-default" id="rename-group-title"><i class="fa fa-pencil-square-o"></i>Rename the group</div>
        <div class="wrapper-action">
          <%= text_field_tag :name, '', class: "input-wrapper input-config", id: "group-config-rename-input", placeholder: "New name" %>
          <input type="submit" value="Rename" class="submit-default submit-config" id="group-config-rename-submit">
        </div>
      </div>

      <div class="config-wrapper" id="config-delete">
        <div class="title-popup-default" id="delete-group-title"><i class="fa fa-times"></i>Delete the group</div>
        <div class="wrapper-action">
          <span class="config-advise"> Deleting this group in an irreversible action</span>
          <%= link_to 'Delete', destroy_group_path(group_id: current_group.id, user_id: current_user.id), class: "submit-default submit-config", id: "group-config-delete-submit",  method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>

      <div class="config-wrapper" id="config-add-user">
      
        <div class="title-popup-default" id="add-user-title"><i class="fa fa-user-plus"></i>Add user</div>

        <div class="wrapper-action" id="config-add-user-token">
          <div class="subtitle-popup-default" id="subtitle-add-one-user">Add users one by one</div>
          <%= form_for Group.new, url: { controller: "groups", action: "send_invitation", group_id: current_group.id }, method: :put do |f| %>
            <%= text_field_tag :name, '', id: "tokenfield", name: 'user[email]', placeholder: "Input your friends name" %>
             <span class="config-advise advise-add-one">Press tab to use the auto-complete</span>
           <!--  <input type="submit" value="Invite" class="submit-default submit-config" id="group-config-add-user-submit"> -->
          <% end %>

        </div>

        <!-- EXCEL IMPORT -->
        <div id="config-exel-import">
          <div class="subtitle-popup-default">Add users through an csv file</div>
          <span class="config-advise">CSV file column: email</span>
          <div class="submit-default submit-config" id="import-excel">Choose a file</div>
          <%= form_tag import_for_involving_users_path(group_id: current_group.id), multipart: true do %>
            <%= file_field_tag :file, id: "pick-excel", class: "hidden" %>
            <%= submit_tag "Invite", class: "hidden", id: "submit-excel" %>
          <% end %>
        </div>
      </div>

    </div>
    <div class="slide-footer">
    </div>
  </div>
</div>

app/views/popup/_popup_new_group.html.erb
<div id="slide-new-group" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <span class="header-title">New group</span>
      <div class="fa fa-close" id="close-new-group"></div>
    </div>
    <div class="slide-body">
      <div class="body-wrapper-new-group">
      <%= text_field_tag :name, '', class: "input-wrapper", id: "new-group-input" %>
      </div>
    </div>
    <div class="slide-footer">
      <input type="submit" value="Create" class="submit-default validate-default" id="new-group-submit">
    </div>
  </div>
</div>

app/views/popup/_popup_signup.html.erb
<div id="slide-signup" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <div class="header-title" id="header-title-sign">
        <span class="header-text">Configure your account</span> 
        <i class="fa fa-lock"></i> 
      </div>

      <div class="fa fa-close" id="close-slide-signup"></div>
    </div>

      
    <div class="slide-body">

      <div id="signup-from-signout-body" class="fadeout-div">
        <i class="fa fa-warning"></i>
        <div class="incoming-text">
          <p>You are using a test version</p>
          <p>All your work will be lost if you don't sign up</p>
        </div>
      </div>

      <div id="signup-from-action-body" class="fadeout-div">
        <i class="fa fa-warning"></i>
        <div class="incoming-text">
          <p>You are using a test version</p>
          <p>This action is not allowed</p>
        </div>
      </div>


      <div id="not-confirmed-account-body" class="fadeout-div">
        <i class="fa fa-warning"></i>
        <div class="incoming-text">
          <p>Hey "" we are happy so see you signed up :)</p>
          <p>To perform this action validate your account first!</p>
        </div>
      </div>


      <div id="signup-username-body" class="fadeout-div">

        <input type="text" class="signup-input" placeholder="Username" id="name" name="user[name]"/>
        <input type="text" class="signup-input" placeholder="Email adress" id="email" name="user[email]"/>

        <div class="password-wrapper">
          <div class="signup-input-wrapper">
            <input type="password" class="signup-input" placeholder="Password" id="password" name="user[password]"/>
            <div class="password-tip">Use at least 6 characters</div>
            <div class="fa fa-check password-notif"></div>
          </div>

          <div id="password-strength" class="short">
            <span class="strength-fixed-text">Password strength:</span>
            <span class="strength-text">Too short</span>
              
            <div class="visual-indicator-container">
              <div class="visual-indicator"></div>
            </div>
          </div>
        </div>

        <div class="signup-input-wrapper">
          <input type="password" class="signup-input" id="password-check" placeholder="Retype" name="user[password_confirmation]">
          <div class="fa fa-check password-check-notif-ok"></div>
          <div class="fa fa-times password-check-notif-bad"></div>
        </div>

        <input id="signup-button" name="commit" type="submit" class="hidden">
      </div>

      <div id="email-check-body" class="fadeout-div">
        <i class="fa fa-bullhorn"></i>
        
        <div class="shouted-text">
          <span class="hey">Congrats <span id="name-after-signup"></span></span>
          <span class="email-sent">Your Unisphere account is ready</span>
        </div>

        <span class="mail-check"><i class="fa fa-envelope"></i>We sent you a validation mail at <span id="email-after-signup"></span> </span>

        <div class="email-note">If you didn't receive your email, we can sent you a <span class="send-new-mail">new one!</span></div>
      </div>
    </div>

    <div class="slide-footer" >

      <div class="footer-signup fadeout-div" id="signup-from-signout-footer">
        <div class="arrow-and-sign-up" id="signout-toward-signup">
          Sign up<i class="fa fa-arrow-right"></i>
        </div>
        <div id="exit-really">skip & exit</div>
      </div>

      <div class="footer-signup fadeout-div" id="signup-from-action-footer">
        <div class="arrow-and-sign-up" id="action-toward-signup">
          Sign up<i class="fa fa-arrow-right"></i>
        </div>
      </div>

      <div class="footer-signup fadeout-div" id="not-confirmed-account-footer">
        <div id="exit-really">skip & exit</div>
      </div>

      <div class="footer-signup fadeout-div" id="signup-username-footer">
        <div class="arrow-and-sign-up" id="toward-confirmation">
          Sign up<i class="fa fa-arrow-right"></i>
        </div>
      </div>

      <div id="email-check-footer" class="fadeout-div other-submit">
       <!--  <div id="back-to-signup">
          <i class="fa fa-arrow-left"></i>Back to sign up
        </div> -->
      </div>
    </div>

  </div>
</div>

app/views/popup/_popup_transfer.html.erb
<div id="slide-transfer-document" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <span class="header-title">File transfer</span>
      <div class="fa fa-close close-transfer-document"></div> 
    </div>
    <div class="slide-body">
      <div class="wrapper-document-to-transfer">
        <div class="document-to-transfer">
          <i class="fa fa-file-o"></i>
          <span id="transfered-item-name">bonjour</span>
        </div>
      </div>
      <div class="arrow-wrapper">
        <div class="fa fa-long-arrow-right"></div>
      </div>
      <div class="wrapper-group-list" id="wrapper-group-list-transfer-document">
        <div class="group-list group-list-transfer-document">
          <% current_groups.each do |group| %>
            <div class="list-element list-element-group-transfer">
              <i class="fa fa-group"></i>
              <span class="list-element-name transfer-list" group_id="<%= group.id %>"><%= group.name %></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="slide-footer">
      <input type="submit" value="Transfer" class="submit-default validate-default" id="transfer-document-submit">
      <!-- <input value="Cancel" class="submit-default close-transfer-document" id="transfer-document-cancel"> -->
    </div>
  </div>
</div>