config/routes.rb
Lms::Application.routes.draw do

  resources :users do
    collection do 
      post :import_for_creating
      post :import_for_involving
    end
		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
		end
    resources :notifications, only: [:index]  
		resources :groups do
      resources :courses, only: [:index, :create, :update, :destroy] do
        resources :evaluations, only: [:create, :update, :destroy] do
          resources :marks, only: [:index, :update]
        end
      end 
			resources :tasks, only: [:create, :edit, :update, :index, :destroy]
		  resources :microposts, only: [:create]
  		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
  			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
  		end
      resources :etherpads, only: [:create, :destroy, :show]
		end
	end	

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'
  
  ############
  ### user ###
  ############
  
  get '/signedup', to: 'users#signedup', as: 'signedup'
  put '/user/update', to: 'users#update', as: 'user_update'
  
  #############
  ### group ###
  #############
  
  put '/user/group/rename', to: 'groups#update', as: 'rename_group'
  delete '/user/group/destroy', to: 'groups#destroy', as: 'destroy_group'
  get 'user/group/autocomplete_user', to: 'groups#autocomplete_user_name', as: 'autocomplete_user_name'
  
  ##################
  ### invitation ###
  ##################
  
  put '/user/group/send_invitation', to: 'groups#send_invitation', as: 'send_invitation'
  get '/user/group/autocomplete', to: 'groups#autocomplete', as: 'autocomplete'
  
  #
  
  get '/confirmation',  to: 'sessions#create'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/signup',  to: 'signup#new'
  get '/signup/team',  to: 'signup#team', as: 'team_setup'


  get '/users/:user_id/allgroups', to: 'groups#show_all', as: 'allgroups'
  post '/user/:user_id/group/:group_id', to: 'groups#join_group', as: 'joingroup'
  delete '/user/:user_id/group/:group_id', to: 'groups#leave_group', as: 'leavegroup'
  
  put '/users/:user_id/viewparams', to: 'viewparams#update', as: 'params'
  
  get '/users/:user_id/groups/:group_id/courses/:course_id/evaluations/:evaluation_id/marks/average', to: 'evaluations#get_average', as: 'get_average_evaluation'
  get '/users/:user_id/groups/:group_id/courses/:course_id/average', to: 'courses#get_average', as: 'get_average_course'
  
  ###############
  ### roadmap ###
  ###############
  
  get '/roadmap',  to: 'sessions#roadmap', as: 'roadmap'
  
  ###########
  ### box ###
  ###########
  
  # oauth
  
  get '/user/send_oauth', to: 'oauths#send_oauth', as: 'send_oauth'
  get '/user/receive_oauth', to: 'oauths#receive_oauth', as: 'receive_oauth'
  get '/user/refresh_token', to: 'oauths#refresh_token', as: 'refresh_token'  
  
  # perso #

  get '/user/documents', to: 'simpledocuments#index', as: 'get_user_documents'
  get '/user/file/download', to: 'simpledocuments#download', as: 'download_user_file'
  get '/user/document/show', to: 'simpledocuments#show', as: 'show_user_file'
  get '/user/document/arianewire', to: 'simpledocuments#ariane_wire', as: 'get_document_ariane_wire'
  get '/user/document/previousfolder', to: 'simpledocuments#previous_folder', as: 'get_user_previous_folder'
  
  post '/user/file/upload', to: 'simpledocuments#upload_file', as: 'upload_user_file'
  post 'user/create_folder', to: 'simpledocuments#create_folder', as: 'create_user_folder'
  post 'user/file/create_shared_link', to: 'simpledocuments#create_shared_link', as: 'create_shared_link'
  
  put '/user/file/rename', to: 'simpledocuments#update', as: 'rename_user_file'
  put '/user/folder/rename', to: 'simpledocuments#update', as: 'rename_user_folder'
  
  put '/user/file/move', to: 'simpledocuments#move_file', as: 'move_user_file'
  put '/user/folder/move', to: 'simpledocuments#move_folder', as: 'move_user_folder'
  
  delete '/user/document/delete', to: 'simpledocuments#destroy', as: 'delete_user_document' 
  
  # group #
  
  get '/user/group/documents', to: 'groupdocuments#read_folder', as: 'get_group_documents'
  get '/user/group/document/download', to: 'groupdocuments#download_file', as: 'download_group_file'
  get '/user/group/document/read', to: 'groupdocuments#read_file', as: 'read_group_file'
  
  post '/user/group/file/create', to: 'groupdocuments#create_file', as: 'create_group_file'
  post '/user/group/folder/create', to: 'groupdocuments#create_folder', as: 'create_group_folder'
  post '/user/group/file/create_shared_link', to: 'groupdocuments#create_shared_link', as: 'create_group_shared_link'
  
  put '/user/group/file/move', to: 'groupdocuments#move_file', as: 'move_group_file'
  put '/user/group/folder/move', to: 'groupdocuments#move_folder', as: 'move_group_folder'
  put '/user/group/file/rename', to: 'groupdocuments#rename_file', as: 'rename_group_file'
  put '/user/group/folder/rename', to: 'groupdocuments#rename_folder', as: 'rename_group_folder'
  put '/user/group/folder/transfer', to: 'groupdocuments#transfer_folder', as: 'transfer_group_folder'
  put '/user/group/file/transfer', to: 'groupdocuments#transfer_file', as: 'transfer_group_file'

  delete '/user/group/document/file/delete', to: 'groupdocuments#destroy_file', as: 'delete_group_file'
  delete '/user/group/document/folder/delete', to: 'groupdocuments#destroy_folder', as: 'delete_group_folder'
  
  ############
  ### chat ###
  ############
  
  get '/user/group/chats', to: 'groupchats#index', as: 'get_group_chats'
  post '/user/group/chat/message/create', to: 'messages#create', as: 'create_message'
  post '/user/group/chat/chat/create', to: 'groupchats#create', as: 'create_chat'
  
  ###############
  ### firepad ###
  ###############
  
  get '/user/group/document/firepad/read', to: 'firepads#read', as: 'read_firepad'
  post '/user/group/document/firepad/create', to: 'firepads#create', as: 'create_firepad'
  
  put '/user/group/document/firepad/rename', to: 'firepads#rename', as: 'rename_firepad'
  put '/user/group/document/firepad/move', to: 'firepads#move', as: 'move_firepad'
  put '/user/group/document/firepad/transfer', to: 'firepads#transfer', as: 'transfer_firepad'
  
  delete '/user/group/document/firepad/destroy', to: 'firepads#destroy', as: 'destroy_firepad'
  
end

app/models/groupdocument.rb
class Groupdocument < ActiveRecord::Base
  
	belongs_to :groupfolder
  
end

app/controllers/groupdocuments_controller.rb
class GroupdocumentsController < ApplicationController
  
  before_action :authenticate?
  before_action :correct_user?
  before_action :has_group?
  before_action :get_folder, only: [:read_folder, :create_file]
  before_action :get_file, only: [:destroy_file]
    
  def read_folder
    
    @group_folders = current_group.groupfolders.where(parent_id: params[:folder_id])
    @new_folder = @folder.groupdocuments.new()
    
    if current_user.id == current_group.admin_id
      @group_documents = @folder.groupdocuments
      @firepads = @folder.firepads
    else
      @group_documents = @folder.groupdocuments.where(admin: true)
      @firepads = @folder.firepads.where(admin: true)
    end
    
    @current_group = current_group
    
    @breadcrumbs = []
    @root = true
    
    @folder = Groupfolder.find params[:folder_id]
    if @folder.parent_id != 100
      @parent = Groupfolder.find @folder.parent_id
      @root = false
    end
    
    if @parent
      while @root != true do
        logger.info @parent.name
        @breadcrumbs << { name: @parent.name, id: @parent.id } if @parent.name != nil
        @parent = if @parent.parent_id != 100 then Groupfolder.find @parent.parent_id else @root = true end
      end
    end
    
    @breadcrumbs = @breadcrumbs.reverse
    logger.info @breadcrumbs
    render "index"
  end
  
  def read_file
    create_link(params[:box_id])
    if @link # owner
      redirect_to @link[:preview_url]
    else # not owner
      document = Groupdocument.where(box_id: params[:box_id]).first
      redirect_to document.share_url
    end
  end
  
  def download_file
    create_link(params[:box_id])
    if @link
      render json: {url: @link[:download_url]}.to_json 
    else
      document = Groupdocument.where(box_id: params[:box_id]).first
      render json: {url: document.share_url}.to_json
    end
  end
  
  def transfer_file
    @file = Groupdocument.find params[:item_id]
    @clone = @file.clone
    @attributes = {
      box_id: @clone.box_id, share_url: @clone.share_url, dl_url: @clone.dl_url, groupfolder_id: @clone.groupfolder_id, name: @clone.name, owner: @clone.owner, size: @clone.size
    }
    @transfered = Groupdocument.new(@attributes)
    @groupfolder = Groupfolder.where(["group_id = :group_id and parent_id = :parent_id", { group_id: params[:group_id], parent_id: 100 }]).first
    @transfered.groupfolder_id = @groupfolder.id
    @transfered.admin = true if Group.find(params[:group_id]).admin_id == current_user.id 
    @transfered.save
    render :nothing => true
  end
  
  def transfer_folder
    @folder = Groupfolder.find params[:item_id]
    @clone = @folder.clone
    @attributes = {
      parent_id: @clone.parent_id, name: @clone.name, group_id: @clone.group_id
    }
    @transfered = Groupfolder.new(@attributes)
    @transfered.group_id = params[:group_id]
    @transfered.parent_id = Groupfolder.where(group_id: params[:group_id]).first.id
    @transfered.save
    render :nothing => true
  end
  
  def rename_file
    @file = Groupdocument.find params[:item_id]
    @file.update(name: params[:name])
    render :nothing => true
  end
  
  def rename_folder
    @folder = Groupfolder.find params[:item_id]
    @folder.update(name: params[:name])
    render :nothing => true
  end
  
  def create_shared_link
    create_link(params[:box_id])
    if @link
      render json: @link[:preview_url]
    else
      document = Groupdocument.where(box_id: params[:box_id]).first
      render json: document.share_url
    end
  end
  
  def create_file
    req_params = {
      attributes: { name: params[:file].original_filename, 
                    parent: {id: 0 }}.to_json,
      file: File.new(params[:file].path)
    }
    
    if !box_content_resources.nil?
      box_content_resources[:upload].post(req_params, :content_type => "application/json") { |response, request, result, &block|
        check_request_success(response)
        return false if @return
      
        if response.code != 409
          @response = JSON.parse(response)
          @doc_params = {
            box_id: @response['entries'].first['id'],
            name: params[:file].original_filename,
            size: @response['entries'].first['size'],
            owner: @response['entries'].first['created_by']['name'],
          }
        elsif response.code == 409
          @search_id = JSON.parse(response)['context_info']['conflicts']['id']
          @need_to_search = true
        end
      }
      
      if @need_to_search == true
        box_content_resources[:basic]["files/#{@search_id}"].get() { |response, request, result, &block|
          check_request_success(response)
          return false if @return
      
          @response = JSON.parse(response)
          @doc_params = {
            box_id: @search_id,
            name: @response['name'],
            size: @response['size'],
            owner: @response['created_by']['name']
          }
        }
      end
      
    else
      send_oauth
      return false
    end
    
    # if !box_content_resources.nil?
    #   if @need_to_search == true
    #     box_content_resources[:basic]["files/#{@search_id}"].get() { |response, request, result, &block|
    #       check_request_success(response)
    #       return false if @return
    #
    #       @response = JSON.parse(response)
    #       @doc_params = {
    #         box_id: @search_id,
    #         name: @response['name'],
    #         size: @response['size'],
    #         owner: @response['created_by']['name']
    #       }
    #     }
    #   end
    # else
    #   send_oauth
    #   return false
    # end
    
    @doc_params[:admin] = true if Group.find(params[:group_id]).admin_id == current_user.id 
    logger.info Group.find(params[:group_id]).admin_id
    logger.info current_user.id
    @folder.groupdocuments.create(@doc_params)
    create_link(@doc_params[:box_id])
    redirect_to get_group_documents_path(group_id: params[:group_id], folder_id: params[:folder_id])

  end
  
  def create_folder
    respond_to do |format|
      if current_group.groupfolders.create(name: 'New Folder', parent_id: params[:folder_id])
     	  format.html { redirect_to get_group_documents_path( groupdocuments_params ) }
     		format.json {  }
      end
   	end
  end
  
  def destroy_file
    @file.update(deleted: true)
    render :nothing => true
  end
  
  def destroy_folder
    @folder = Groupfolder.find params[:folder_id]
    @folder.groupdocuments.each { |file| file.update(deleted: true)}
    Groupfolder.where(parent_id: @folder.id).each { |folder| folder.destroy}
    @folder.destroy
    render :nothing => true
  end
  
  def move_file
    @file = Groupdocument.find params[:dragged]
    @file.update_attributes(groupfolder_id: params[:dropped])
    render :nothing => true
  end
  
  def move_folder
    @folder = Groupfolder.find params[:dragged]
    @folder.update_attributes(parent_id: params[:dropped])
    render :nothing => true
  end
  
  private
  
  def groupdocuments_params
    { 
      group_id: params[:group_id],
      folder_id: params[:folder_id]
    }
  end
  
  def get_file
    @file = Groupdocument.find params[:file_id]
  end
  
  def get_folder
    if params[:parent_id]
      @folder = current_group.groupfolders.find_by parent_id: params[:parent_id]
      params[:folder_id] = @folder.id
    else
      @folder = current_group.groupfolders.find params[:folder_id]
    end
  end
  
end

app/views/groupdocuments/index.html.erb
<div id="container-perso-storage">

	<!-- ------ -->
	<!-- HEADER -->
	<!-- ------ -->

	<div class="first-row">
		<div id="breadcrumb" folder_id="<%= @folder.id %>" group_id="<%= params[:group_id] %>" group_name="<%= @current_group.name %>" >
			
			<% @breadcrumbs.each do |document| %>
				<%= link_to document[:name], get_group_documents_path(folder_id: document[:id], group_id: params[:group_id]), class: "breadcrumb-redirection name-document" %>
				<span class="breadcrumb-separator"> > </span>
			<% end %>
		</div>

		<span id="prompt-signup">
			<% if !current_user.confirmation.email_confirmed %>
				<% if current_user.created_at == current_user.updated_at %>
					This is a test version! &nbsp &nbsp For full features &nbsp &nbsp<span id="signup-button-navbar"><i class="fa fa-paw"></i>Sign up</span>
				<% else %>
					Your account is not validated yet! &nbsp &nbsp Check your mails
				<% end %>
			<% end %>
		</span>

		<!--<div id="perso-file-search" class="col-md-4">-->
			<!--  <span class="icon"><i class="fa fa-search"></i></span>-->
			<!--  <input type="search" id="search" placeholder="Search..." />-->
			<!--</div>-->
    
		</div> 

		<div class="main-page">
			<div class="separator"></div>
      
			
			<!-- ------------- -->
			<!-- DOCUMENT list -->
			<!-- ------------- -->

    <div id="list-document">
      <div class="notification-row"></div>
      <div id="loader" class="hidden">Loading...</div>
      <div id="list-title">
        <div id="title-name" class="cloud-title">
          <span class="title-text">Name</span>
          <span class="fa fa-sort-up"></span>
        </div>
        <div id="title-modified" class="cloud-title">
          <span class="title-text">Last modified</span>
          <span class="fa fa-sort-up"></span>
        </div>
        <div id="title-size" class="cloud-title">
          <span class="title-text">Size</span>
          <span class="fa fa-sort-up"></span>
        </div>
      </div>
				
      <div class="document-rows">
	
        <% @group_folders.each do |folder| %>
    	    <div class="box_document" document-selected="false">
            <span class="dragAndDrop icon-and-name" item_id="<%= folder.id %>" item="folder" name="<%= folder.name %>" >
              <%= link_to get_group_documents_path(group_id: params[:group_id], folder_id: folder.id) do %>
                <%= fa_icon("folder-o") %>
                <span class="name-document go-folder"><%= folder.name %></span>
              <% end %>
              <%= text_field_tag :name, folder.name, class: "hidden input-rename-document" %>
            </span>
            
            <a title="Rename" rel="nofollow"><%= fa_icon("pencil", class: "document-rename") %></a>
            <div class="modified-doc">
              <span class="date-time"><%= time_ago_in_words Time.at(folder.created_at.to_i) %></span>
              <span class="person"></span>
            </div>
            <div class="size-doc">-&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</div>
          </div>
        <% end %>
			
	
				<% @group_documents.each do |document| %>
  				<% if document.deleted == false && document.name %>
  				<div class="box_document" document-selected="false">
  					<span class="dragAndDrop icon-and-name" document_id="<%= document.box_id %>" item="file" name="<%= document.name %>" item_id="<%= document.id %>"%>
  						<%= link_to read_group_file_path(box_id: document.box_id) do %>
  						<%= fa_icon("file-o") %>
  						<span class="name-document"> <%= document.name %> </span>
  						<% end %>
  						<%= text_field_tag :name, document.name, class: "hidden input-rename-document" %>
  					</span>
              
  					<a title="Rename" rel="nofollow"><%= fa_icon("pencil", class: "document-rename") %></a>
  					<div class="modified-doc">
  						<span class="date-time"><%= time_ago_in_words Time.at(document.created_at.to_i) %></span>
  						<span class="person"><%= document.owner %></span>
  					</div>
  					<div class="size-doc"><%= document.size/1000 %> kb</div>
  				</div>
  				<% end %>
				<% end %>

		
        <% @firepads.each do |firepad| %>
  				<% if firepad.deleted == false %>
      	    <div class="box_document" document-selected="false">
              <span class="dragAndDrop icon-and-name" item_id="<%= firepad.id %>" item="firepad" item_id="<%= firepad.id %>" name="<%= firepad.name %>" firepad_ref="<%= firepad.firebase_url %>">
                <%= link_to read_firepad_path(firepad_id: firepad.id, group_id: current_group.id) do %>
                  <%= fa_icon("edit") %>
                  <span class="name-document go-file"><%= firepad.name %></span>
                <% end %>
                <%= text_field_tag :name, firepad.name, class: "hidden input-rename-document" %>
              </span>
              
              <a title="Rename" rel="nofollow"><%= fa_icon("pencil", class: "document-rename") %></a>
              <div class="modified-doc">
                <span class="date-time"><%= time_ago_in_words Time.at(firepad.created_at.to_i) %></span>
                <span class="person"></span>
              </div>
              <div class="size-doc">-&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</div>
            </div>
          <% end %>
				<% end %>
      </div>
    </div> 
		
    <!-- ------------------- -->
    <!-- ACTIONS             -->
    <!-- ------------------- -->

    <div id="right-actions">

      <div id="new-actions">
        <div class="action-doc action-possible" id="actions-creation" >
          <%= link_to create_group_folder_path(group_id: params[:group_id], folder_id: params[:folder_id]), method: :post, id:"new-folder", class:"action", title:"Create a folder" do%>
              <%= fa_icon "folder-o" %>
          <% end %>

          <a id="upload-doc" rel="nofollow" class="action" title="Upload a doc">
            <%= fa_icon("arrow-circle-o-up") %>
          </a>
          <%= form_tag create_group_file_path(group_id: params[:group_id], folder_id: params[:folder_id]), multipart: true do %>
            <%= file_field_tag :file, id: "input-button-upload", class: "hidden" %>
            <%= submit_tag "upload-doc", class: "hidden", id: "submit-button-upload" %>
          <% end %>

          <a id="create-firepad" class="action" title="Create a collaborative document" rel="nofollow">
            <i class="fa fa-edit"></i>
          </a>
        </div>
        <div class="action-doc" id="actions-selected-doc">
          <a id="download-doc" class="action" rel="nofollow" title="Download a document">
            <%= fa_icon("arrow-circle-o-down") %>
          </a>
          <a id="delete-doc" class="action" rel="nofollow" title="Delete a document">
            <%= fa_icon("trash-o") %>
          </a>
          <a id="link-doc" class="action" rel="nofollow" title="Share a document">
            <%= fa_icon("link") %>
          </a>
          <a id="transfer-file" class="action" rel="nofollow" title="Transfer a document">
            <%= fa_icon("exchange") %>
          </a>
          <div id="link-display"></div>
        </div>
      </div>
    </div>
  </div>
</div>