config/routes.rb
Lms::Application.routes.draw do

  resources :users do
    collection do 
      post :import_for_creating
      post :import_for_involving
    end
		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
		end
    resources :notifications, only: [:index]  
		resources :groups do
      resources :courses, only: [:index, :create, :update, :destroy] do
        resources :evaluations, only: [:create, :update, :destroy] do
          resources :marks, only: [:index, :update]
        end
      end 
			resources :tasks, only: [:create, :edit, :update, :index, :destroy]
		  resources :microposts, only: [:create]
  		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
  			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
  		end
      resources :etherpads, only: [:create, :destroy, :show]
		end
	end	

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'
  
  ############
  ### user ###
  ############
  
  get '/signedup', to: 'users#signedup', as: 'signedup'
  put '/user/update', to: 'users#update', as: 'user_update'
  
  #############
  ### group ###
  #############
  
  put '/user/group/rename', to: 'groups#update', as: 'rename_group'
  delete '/user/group/destroy', to: 'groups#destroy', as: 'destroy_group'
  get 'user/group/autocomplete_user', to: 'groups#autocomplete_user_name', as: 'autocomplete_user_name'
  
  ##################
  ### invitation ###
  ##################
  
  put '/user/group/send_invitation', to: 'groups#send_invitation', as: 'send_invitation'
  get '/user/group/autocomplete', to: 'groups#autocomplete', as: 'autocomplete'
  
  #
  
  get '/confirmation',  to: 'sessions#create'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/signup',  to: 'signup#new'
  get '/signup/team',  to: 'signup#team', as: 'team_setup'


  get '/users/:user_id/allgroups', to: 'groups#show_all', as: 'allgroups'
  post '/user/:user_id/group/:group_id', to: 'groups#join_group', as: 'joingroup'
  delete '/user/:user_id/group/:group_id', to: 'groups#leave_group', as: 'leavegroup'
  
  put '/users/:user_id/viewparams', to: 'viewparams#update', as: 'params'
  
  get '/users/:user_id/groups/:group_id/courses/:course_id/evaluations/:evaluation_id/marks/average', to: 'evaluations#get_average', as: 'get_average_evaluation'
  get '/users/:user_id/groups/:group_id/courses/:course_id/average', to: 'courses#get_average', as: 'get_average_course'
  
  ###############
  ### roadmap ###
  ###############
  
  get '/roadmap',  to: 'sessions#roadmap', as: 'roadmap'
  
  ###########
  ### box ###
  ###########
  
  # oauth
  
  get '/user/send_oauth', to: 'oauths#send_oauth', as: 'send_oauth'
  get '/user/receive_oauth', to: 'oauths#receive_oauth', as: 'receive_oauth'
  get '/user/refresh_token', to: 'oauths#refresh_token', as: 'refresh_token'  
  
  # perso #

  get '/user/documents', to: 'simpledocuments#index', as: 'get_user_documents'
  get '/user/file/download', to: 'simpledocuments#download', as: 'download_user_file'
  get '/user/document/show', to: 'simpledocuments#show', as: 'show_user_file'
  get '/user/document/arianewire', to: 'simpledocuments#ariane_wire', as: 'get_document_ariane_wire'
  get '/user/document/previousfolder', to: 'simpledocuments#previous_folder', as: 'get_user_previous_folder'
  
  post '/user/file/upload', to: 'simpledocuments#upload_file', as: 'upload_user_file'
  post 'user/create_folder', to: 'simpledocuments#create_folder', as: 'create_user_folder'
  post 'user/file/create_shared_link', to: 'simpledocuments#create_shared_link', as: 'create_shared_link'
  
  put '/user/file/rename', to: 'simpledocuments#update', as: 'rename_user_file'
  put '/user/folder/rename', to: 'simpledocuments#update', as: 'rename_user_folder'
  
  put '/user/file/move', to: 'simpledocuments#move_file', as: 'move_user_file'
  put '/user/folder/move', to: 'simpledocuments#move_folder', as: 'move_user_folder'
  
  delete '/user/document/delete', to: 'simpledocuments#destroy', as: 'delete_user_document' 
  
  # group #
  
  get '/user/group/documents', to: 'groupdocuments#read_folder', as: 'get_group_documents'
  get '/user/group/document/download', to: 'groupdocuments#download_file', as: 'download_group_file'
  get '/user/group/document/read', to: 'groupdocuments#read_file', as: 'read_group_file'
  
  post '/user/group/file/create', to: 'groupdocuments#create_file', as: 'create_group_file'
  post '/user/group/folder/create', to: 'groupdocuments#create_folder', as: 'create_group_folder'
  post '/user/group/file/create_shared_link', to: 'groupdocuments#create_shared_link', as: 'create_group_shared_link'
  
  put '/user/group/file/move', to: 'groupdocuments#move_file', as: 'move_group_file'
  put '/user/group/folder/move', to: 'groupdocuments#move_folder', as: 'move_group_folder'
  put '/user/group/file/rename', to: 'groupdocuments#rename_file', as: 'rename_group_file'
  put '/user/group/folder/rename', to: 'groupdocuments#rename_folder', as: 'rename_group_folder'
  put '/user/group/folder/transfer', to: 'groupdocuments#transfer_folder', as: 'transfer_group_folder'
  put '/user/group/file/transfer', to: 'groupdocuments#transfer_file', as: 'transfer_group_file'

  delete '/user/group/document/file/delete', to: 'groupdocuments#destroy_file', as: 'delete_group_file'
  delete '/user/group/document/folder/delete', to: 'groupdocuments#destroy_folder', as: 'delete_group_folder'
  
  ############
  ### chat ###
  ############
  
  get '/user/group/chats', to: 'groupchats#index', as: 'get_group_chats'
  post '/user/group/chat/message/create', to: 'messages#create', as: 'create_message'
  post '/user/group/chat/chat/create', to: 'groupchats#create', as: 'create_chat'
  
  ###############
  ### firepad ###
  ###############
  
  get '/user/group/document/firepad/read', to: 'firepads#read', as: 'read_firepad'
  post '/user/group/document/firepad/create', to: 'firepads#create', as: 'create_firepad'
  
  put '/user/group/document/firepad/rename', to: 'firepads#rename', as: 'rename_firepad'
  put '/user/group/document/firepad/move', to: 'firepads#move', as: 'move_firepad'
  put '/user/group/document/firepad/transfer', to: 'firepads#transfer', as: 'transfer_firepad'
  
  delete '/user/group/document/firepad/destroy', to: 'firepads#destroy', as: 'destroy_firepad'
  
end

app/controllers/simpledocuments_controller.rb
class SimpledocumentsController < ApplicationController
  
  before_action :authenticate?
  before_action :force_under_construction

  def create_folder
    req_params = {
      name: "New Folder",
      parent: { id: params[:folder] }
    }

    box_content_resources[:basic]["folders"].post(req_params.to_json) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
    }
    redirect_to get_user_documents_path(folder: params[:folder])
  end
  
  def create_shared_link
    create_link(params[:box_id])
    render json: @link[:preview_url]
  end
  
  def previous_folder
    box_content_resources[:basic]["folders/#{params[:box_id]}"].get() { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
      @parent = JSON.parse(response)['parent']['id']
    }
    redirect_to get_user_documents_path(folder: @parent)
  end
  
  def update
    req_params = {
      name: params[:name]
    }
    
    params[:type] == "folder" ? @box_object = 'folders' : @box_object = 'files'
      
    box_content_resources[:basic]["#{@box_object}/#{params[:box_id]}"].put(req_params.to_json) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
      logger.info response
    }
    render nothing: true
  end
  
  def index
    req_params = { 
      fields: "id,name,created_at,modified_at,size,type"
    }

    box_content_resources[:basic]["folders/#{params[:folder]}/items"].get(params: req_params) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
      @folder_name = JSON.parse(response)['name']
      @documents = []
      JSON.parse(response)['entries'].each do |file|
        @documents << file
      end
    }
  end

  def upload_file
    req_params = {
      attributes: { name: params[:file].original_filename, 
                    parent: {id: params[:folder] }}.to_json,
      file: File.new(params[:file].path)
    }

    box_content_resources[:upload].post(req_params, :content_type => "application/json") { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
    }
    redirect_to get_user_documents_path(folder: params[:folder])
  end

  def download
    box_content_resources[:basic]["files/#{params[:box_id]}/content"].get() { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
      @dl_url = response.headers[:location]
    }
    
    respond_to do |format|
      format.html { redirect_to(@dl_url) }
      format.json { render json: {url: @dl_url}.to_json }
    end
    
  end
  
  def show
    create_link(params[:box_id])
    redirect_to @link[:preview_url]
  end
  
  def destroy
    logger.info params[:type]
    params[:type] == "folder" ? @box_object = 'folders' : @box_object = 'files'
    
    box_content_resources[:basic]["#{@box_object}/#{params[:box_id]}"].delete(params: {recursive: true}) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
      @response = response.code
    }
    render json: @response  
  end
  

  def move_file
    req_params = {
      parent: { id: params[:dropped] }
    }
    box_content_resources[:basic]["files/#{params[:dragged]}"].put(req_params.to_json) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
    }
    render nothing: true
  end
  
  def move_folder
    req_params = {
      parent: { id: params[:dropped] }
    }
    box_content_resources[:basic]["folders/#{params[:dragged]}"].put(req_params.to_json) { |response, request, result, &block|
      check_request_success(response)
      return false if @return
      
    }
    render nothing: true
  end
  
  def ariane_wire
    @ariane_wire = {}
    @parent_id = params[:box_id]
    @i = 0
    
    until @parent_id == '0'
      box_content_resources[:basic]["folders/#{@parent_id}"].get() { |response, request, result, &block|
        check_request_success(response)
        return false if @return
      
        @parent_id = JSON.parse(response)['parent']['id'] if JSON.parse(response)['parent']
        @ariane_wire[@i] = { name: JSON.parse(response)['name'], id: JSON.parse(response)['id'] }
        @i+=1
      }
    end
    
    respond_to do |format|
      format.html { render json: @ariane_wire }
      format.json { render json: @ariane_wire }
    end
  end
  
  private
  
	def document_params
    params.require(:document).permit(:folder, :id, :type)
  end
  
end

app/views/simpledocuments/index.html.erb
<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css"> -->
<div id="container-perso-storage">

	<!-- ------ -->
	<!-- HEADER -->
	<!-- ------ -->

	<div class="first-row" id="breadcrumb-seachbar">
		<div id="breadcrumb" folder_id="<%= params[:folder] %>" >
		</div>
		

		<!--<div id="perso-file-search" class="col-md-4">-->
			<!--  <span class="icon"><i class="fa fa-search"></i></span>-->
			<!--  <input type="search" id="search" placeholder="Search..." />-->
			<!--</div>-->
    
		</div> 

		<div class="main-page">
			<div class="separator"></div>
      
			
			<!-- ------------- -->
			<!-- DOCUMENT list -->
			<!-- ------------- -->

    <div id="list-document">
      <div class="notification-row"></div>
      <div id="loader" class="hidden"></div>
      <div id="list-title">
        <div id="title-name" class="cloud-title">
          <span class="title-text">Name</span>
          <span class="fa fa-sort-up"></span>
        </div>
        <div id="title-modified" class="cloud-title">
          <span class="title-text">Last modified</span>
          <span class="fa fa-sort-up"></span>
        </div>
        <div id="title-size" class="cloud-title">
          <span class="title-text">Size</span>
          <span class="fa fa-sort-up"></span>
        </div>
      </div>

      <% @documents.each do |document| %>
        <div class="box_document" document-selected="false">
          <span class="dragAndDrop icon-and-name" document_id="<%= document['id'] %>" item="<%= document['type'] %>" name="<%= document['name'] %>" >
            <% if document['type'] == 'folder' %>
              <%= link_to get_user_documents_path(folder: document['id']) do %>
                <%= fa_icon("folder-o") %>
                <span class="name-document go-folder"> <%= document['name'] %> </span>
              <% end %>
            <% elsif document['type'] == 'file' %>
              <%= link_to show_user_file_path(box_id: document['id']), file: document.to_json , item: 'folder' do %>
                <%= fa_icon("file-o") %>
               <span class="name-document go-file"> <%= document['name'] %> </span>
              <% end %>
            <% end %>
            <%= text_field_tag :name, document['name'], class: "hidden input-rename-document" %>
          </span>

          <%= fa_icon("pencil", class: "document-rename") %>
          <div class="modified-doc">
            <span class="date-time"><%= time_ago_in_words(document['created_at']) %></span>
            <span class="person"><%= current_user.name %></span>
          </div>
          <div class="size-doc"><%= document['size']/1000 %> kb</div>
          <!-- <div class="file-separator"></div> -->
        </div>
      <% end %>
      
    </div> 

    <!-- ------------------- -->
    <!-- ACTIONS             -->
    <!-- ------------------- -->

    <div id="right-actions">

      <div id="new-doc" class="">
        <%= fa_icon("4x plus-square-o")%>
        <div id="new-actions">
          <%= link_to create_user_folder_path(folder: params[:folder]), method: :post, id:"new-folder" do%>
            <%= fa_icon "folder-o" %>Folder
          <% end %>

          <a id="upload-doc" rel="nofollow"><i class="fa fa-arrow-circle-o-up"></i>Upload</a>
          <%= form_tag upload_user_file_path(folder: params[:folder]), multipart: true do %>
            <%= file_field_tag :file, class: "hidden", id: "input-button-upload" %>
            <%= submit_tag "upload", class: "hidden", id: "submit-button-upload" %>
          <% end %>
          <div id="create-doc">
            <a class="create-list"><i class="fa fa-fire"></i>Firepad</a>
            <!-- <a class="create-list"><i class="fa fa-file-o"></i>Google doc</a> -->
          </div>
        </div>
      </div>
      
      <div id="actions-doc">
        <div id="download-doc" class="action">
          <%= fa_icon("2x arrow-circle-o-down") %>
        </div>
        <div id="delete-doc" class="action">
          <%= fa_icon("2x trash-o") %>
        </div>
        <div id="link-doc" class="action">
          <%= fa_icon("2x link") %>
        </div>
        <div id="link-display"></div>
      </div>
    </div>
  </div>
</div>