config/routes.rb
Lms::Application.routes.draw do

  resources :users do
    collection do 
      post :import_for_creating
      post :import_for_involving
    end
		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
		end
    resources :notifications, only: [:index]  
		resources :groups do
      resources :courses, only: [:index, :create, :update, :destroy] do
        resources :evaluations, only: [:create, :update, :destroy] do
          resources :marks, only: [:index, :update]
        end
      end 
			resources :tasks, only: [:create, :edit, :update, :index, :destroy]
		  resources :microposts, only: [:create]
  		resources :calendars, only: [:new, :create, :destroy, :index, :show] do
  			resources :events, only: [:create, :new, :update, :edit, :destroy, :index]
  		end
      resources :etherpads, only: [:create, :destroy, :show]
		end
	end	

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'sessions#new'
  
  ############
  ### user ###
  ############
  
  get '/signedup', to: 'users#signedup', as: 'signedup'
  put '/user/update', to: 'users#update', as: 'user_update'
  
  #############
  ### group ###
  #############
  
  put '/user/group/rename', to: 'groups#update', as: 'rename_group'
  delete '/user/group/destroy', to: 'groups#destroy', as: 'destroy_group'
  get 'user/group/autocomplete_user', to: 'groups#autocomplete_user_name', as: 'autocomplete_user_name'
  
  ##################
  ### invitation ###
  ##################
  
  put '/user/group/send_invitation', to: 'groups#send_invitation', as: 'send_invitation'
  get '/user/group/autocomplete', to: 'groups#autocomplete', as: 'autocomplete'
  
  #
  
  get '/confirmation',  to: 'sessions#create'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/signup',  to: 'signup#new'
  get '/signup/team',  to: 'signup#team', as: 'team_setup'


  get '/users/:user_id/allgroups', to: 'groups#show_all', as: 'allgroups'
  post '/user/:user_id/group/:group_id', to: 'groups#join_group', as: 'joingroup'
  delete '/user/:user_id/group/:group_id', to: 'groups#leave_group', as: 'leavegroup'
  
  put '/users/:user_id/viewparams', to: 'viewparams#update', as: 'params'
  
  get '/users/:user_id/groups/:group_id/courses/:course_id/evaluations/:evaluation_id/marks/average', to: 'evaluations#get_average', as: 'get_average_evaluation'
  get '/users/:user_id/groups/:group_id/courses/:course_id/average', to: 'courses#get_average', as: 'get_average_course'
  
  ###############
  ### roadmap ###
  ###############
  
  get '/roadmap',  to: 'sessions#roadmap', as: 'roadmap'
  
  ###########
  ### box ###
  ###########
  
  # oauth
  
  get '/user/send_oauth', to: 'oauths#send_oauth', as: 'send_oauth'
  get '/user/receive_oauth', to: 'oauths#receive_oauth', as: 'receive_oauth'
  get '/user/refresh_token', to: 'oauths#refresh_token', as: 'refresh_token'  
  
  # perso #

  get '/user/documents', to: 'simpledocuments#index', as: 'get_user_documents'
  get '/user/file/download', to: 'simpledocuments#download', as: 'download_user_file'
  get '/user/document/show', to: 'simpledocuments#show', as: 'show_user_file'
  get '/user/document/arianewire', to: 'simpledocuments#ariane_wire', as: 'get_document_ariane_wire'
  get '/user/document/previousfolder', to: 'simpledocuments#previous_folder', as: 'get_user_previous_folder'
  
  post '/user/file/upload', to: 'simpledocuments#upload_file', as: 'upload_user_file'
  post 'user/create_folder', to: 'simpledocuments#create_folder', as: 'create_user_folder'
  post 'user/file/create_shared_link', to: 'simpledocuments#create_shared_link', as: 'create_shared_link'
  
  put '/user/file/rename', to: 'simpledocuments#update', as: 'rename_user_file'
  put '/user/folder/rename', to: 'simpledocuments#update', as: 'rename_user_folder'
  
  put '/user/file/move', to: 'simpledocuments#move_file', as: 'move_user_file'
  put '/user/folder/move', to: 'simpledocuments#move_folder', as: 'move_user_folder'
  
  delete '/user/document/delete', to: 'simpledocuments#destroy', as: 'delete_user_document' 
  
  # group #
  
  get '/user/group/documents', to: 'groupdocuments#read_folder', as: 'get_group_documents'
  get '/user/group/document/download', to: 'groupdocuments#download_file', as: 'download_group_file'
  get '/user/group/document/read', to: 'groupdocuments#read_file', as: 'read_group_file'
  
  post '/user/group/file/create', to: 'groupdocuments#create_file', as: 'create_group_file'
  post '/user/group/folder/create', to: 'groupdocuments#create_folder', as: 'create_group_folder'
  post '/user/group/file/create_shared_link', to: 'groupdocuments#create_shared_link', as: 'create_group_shared_link'
  
  put '/user/group/file/move', to: 'groupdocuments#move_file', as: 'move_group_file'
  put '/user/group/folder/move', to: 'groupdocuments#move_folder', as: 'move_group_folder'
  put '/user/group/file/rename', to: 'groupdocuments#rename_file', as: 'rename_group_file'
  put '/user/group/folder/rename', to: 'groupdocuments#rename_folder', as: 'rename_group_folder'
  put '/user/group/folder/transfer', to: 'groupdocuments#transfer_folder', as: 'transfer_group_folder'
  put '/user/group/file/transfer', to: 'groupdocuments#transfer_file', as: 'transfer_group_file'

  delete '/user/group/document/file/delete', to: 'groupdocuments#destroy_file', as: 'delete_group_file'
  delete '/user/group/document/folder/delete', to: 'groupdocuments#destroy_folder', as: 'delete_group_folder'
  
  ############
  ### chat ###
  ############
  
  get '/user/group/chats', to: 'groupchats#index', as: 'get_group_chats'
  post '/user/group/chat/message/create', to: 'messages#create', as: 'create_message'
  post '/user/group/chat/chat/create', to: 'groupchats#create', as: 'create_chat'
  
  ###############
  ### firepad ###
  ###############
  
  get '/user/group/document/firepad/read', to: 'firepads#read', as: 'read_firepad'
  post '/user/group/document/firepad/create', to: 'firepads#create', as: 'create_firepad'
  
  put '/user/group/document/firepad/rename', to: 'firepads#rename', as: 'rename_firepad'
  put '/user/group/document/firepad/move', to: 'firepads#move', as: 'move_firepad'
  put '/user/group/document/firepad/transfer', to: 'firepads#transfer', as: 'transfer_firepad'
  
  delete '/user/group/document/firepad/destroy', to: 'firepads#destroy', as: 'destroy_firepad'
  
end

app/helpers/layouts_helper.rb
module LayoutsHelper

  def current_groups
    current_user.nil? ? nil : current_groups = current_user.groups.all
  end
  
  def group_calendar
    current_group.nil? ? nil : group_calendar = current_group.calendar
  end
  
  def current_group
    current_group = current_user.groups.find(params[:group_id])
  end

  
  def current_group_exists?
    current_user.groups.exists?(params[:group_id])
  end
  
  def current_user_notification_view
    current_user_notification_view = Time.at(current_user.viewparam.notification_view).utc
  end
    
  def notification_exists?
    current_groups.each do |group|
      @answer = true if PublicActivity::Activity.exists?(['owner_id = ? and updated_at > ?', group.id, current_user_notification_view])
    end
    return @answer
  end
  
end

app/views/layouts/_header.html.erb
<header class="navbar" data-activeslide="1" role="navigation">
	<!-- Firebase -->
	<script src="https://cdn.firebase.com/js/client/2.0.2/firebase.js"></script>

	<!-- CodeMirror -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.3.0/codemirror.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.3.0/codemirror.css" />

	<!-- Firepad -->
	<link rel="stylesheet" href="https://cdn.firebase.com/libs/firepad/1.1.0/firepad.css" />
	<script src="https://cdn.firebase.com/libs/firepad/1.1.0/firepad.min.js"></script>
  <div class="logo">
    <a href="<%= root_path %>">
      <object type="image/svg+xml" data="<%= asset_path 'mickey_2.svg' %>" id="logo"></object>
    </a>
  </div>

  <% if @title == "home" %> 
		<div class="nav-middle">
			<a data-slide="1" class="item-nav" id="menu-link-1" href="#slide-1" >
        <span class="fa fa-home"></span> 
        <span class="text-nav">HOME</span>
      </a>
      <!-- <a data-slide="2" class="item-nav" id="menu-link-2" href="#slide-2" >
        <span class="fa fa-eye"></span> 
        <span class="text-nav">OVERVIEW</span>
      </a> -->
      <a data-slide="2" class="item-nav" id="menu-link-2" href="#slide-2" >
        <span class="fa fa-gears"></span> 
        <span class="text-nav">FEATURES</span>
      </a>
      <a data-slide="3" class="item-nav" id="menu-link-3" href="#slide-3" >
        <span class="fa fa-envelope"></span> 
        <span class="text-nav">CONTACT</span>
      </a>
			
			<div class="active-menu"></div>
    </div>

    <div class="nav-right">
      <a href="<%= roadmap_path %>" class="right-nav-item">
        <span class="fa fa-bus"></span>
        <span class="text">ROADMAP</span>
      </a>
      <!-- <a href="#" class="right-nav-item clients-path">
        <span class="fa fa-heart"></span>
        <span class="text">CLIENTS</span>
      </a> -->
    </div>
  
  <% end %>

  
</header>

app/views/layouts/_navbar.html.erb
    <div id="logo-wrapper">
    <!-- <svg width="24" height="24">
        <image xlink:href="mickey.svg" width="24" height="24" />
      </svg> -->
      <!-- <object type="image/svg+xml" data="<%= asset_path 'mickey_2.svg' %>"></object> -->
      <!-- <span class= "brand&#45;name"> INFINITREE </span> -->
    </div>

    


    <div id="user-deco">
      <a id="user-profile" >
        <!-- <object type="image/svg+xml" data="<%#= asset_path 'pic-default-28.svg' %>" id="profile-pic"></object> -->
        <% if current_user.confirmation.email_confirmed %>
          <span id="profile-pic" class="fa fa-user"></span>
        <% else %>
          <span id="profile-pic" class="fa fa-user-secret"></span>
        <% end %>
        <span class="user-name" current_user_name="<%= current_user.name %>" current_user_id="<%= current_user.id %>"><%= current_user.name %></span>
      </a>
     	
			<span class="deco fa fa-sign-out" id="deco"></span>
      
    </div>

		<%= link_to 'oauth', send_oauth_path, style: "color: white" %>

app/views/layouts/_sidebar.html.erb
<div id="tabs-container">
	<%= link_to 'Perso', get_user_documents_path(folder: '0' ) , class: "tab #{url_perso?}", id: "tab-perso", current_user_id: current_user.id %>
	<%= link_to 'Groups', get_group_documents_path(group_id: current_user.groups.last, parent_id: 100), class: "tab #{url_groups?}", id: "tab-group" %>
</div>

<div id="row-and-content-wrapper">
	<div id="sidebar-first-row">
		<span id="uni-name">Université de Strasbourg</span>
	</div>
	<div id="content-wrapper">

		<div class="separator"></div>

		<% if request.url.include? 'group' %>
			<% if current_group_exists? %>
				<div class="lateral-nav" id="active-group-nav" group_id="<%= current_group.id %>">
					<div id="current-group-wrapper" class="subtitle-default">
						<div class="name-text" id="current-group-title"><%=current_group.name%></div>
						<div class="fa fa-gear" id="current-group-config"></div>
					</div> 
					<div class="active-menu"></div>
					<a href="<%= get_group_documents_path(group_id: params[:group_id], parent_id: 100) %>" data-space="1" class="lateral-nav-element <%= 'active' if current_page?(get_group_documents_path(group_id: params[:group_id], parent_id: 100)) %> <%= 'previous' if url_for(:back) == get_group_documents_url(group_id: params[:group_id], parent_id: 100) %>">
						<i class="fa fa-folder-open-o"></i>Folder
					</a>

					<a href="<%= get_group_chats_path(group_id: params[:group_id]) %>" data-space="2" class="lateral-nav-element <%= 'active' if current_page?(get_group_chats_path) %> <%= 'previous' if url_for(:back) == get_group_chats_url %>">
						<i class="fa fa-wechat"></i>Chat
					</a>

					<a href="<%= user_group_calendar_path(current_user, current_group, group_calendar) %>" data-space="3" class="lateral-nav-element  <%= 'active' if current_page?(user_group_calendar_path(current_user, current_group, group_calendar)) %> <%= 'previous' if url_for(:back) == user_group_calendar_url(current_user, current_group, group_calendar) %>">
						<i class="fa fa-calendar"></i>Calendar
					</a>
	      </div>
			<%end%>


			<div class="lateral-nav" id="groups-nav" >
				<div id="current-group-wrapper" class="subtitle-default">
						<div class="name-text">Other groups</div>
						<div class="fa fa-plus"  id="new-group"></div>
				</div> 
				
				<div class="sidebar-list-group">
					<% current_groups.each do |group| %>
						<%= link_to get_group_documents_path(group_id: group.id, parent_id: 100), class: "lateral-nav-element current-group-element" do %>
							<i class="fa fa-group"></i>
							<!-- <object type="image/svg+xml" data="<%= asset_path 'group-pic.svg' %>" id="profile-pic"></object> -->
							<span class="group-name-sidebar" group_id="<%= group.id %>"><%= group.name %></span>
						<% end %>
					<% end %>
				</div>
				<!-- <div class="line-separator"></div> -->
				<div id="all-groups"><i class="fa fa-eye"></i>See all groups</div>
			</div>

		<% elsif %>
			<div class="lateral-nav" id="nav-perso">
				<div class="subtitle-default">
						<div class="name-text"><%=current_user.name%></div>
						<div class="fa fa-gear"></div>
					</div>
				<!-- <div class="section-title">Tools</div> -->
				<div class="active-menu"></div>

				<a href="<%= get_user_documents_path(folder: '0') %>" data-space="1" class="lateral-nav-element <%= 'active' if current_page?(get_user_documents_path(folder: '0')) %> <%= 'previous' if url_for(:back) == get_user_documents_url(folder: '0') %>">
					<i class="fa fa-folder-open-o"></i>Folder
				</a>
				

				<a href="<%= get_user_documents_path(folder: '0') %>" data-space="2" class="lateral-nav-element <%= 'active' if current_page?(user_path(current_user)) %> <%= 'previous' if url_for(:back) == user_url(current_user) %>">
					<i class="fa fa-wechat"></i>Chat
				</a>

				<a data-space="3" href="<%= user_calendars_path(current_user) %>" class="lateral-nav-element <%= 'active' if current_page?(user_calendars_path(current_user)) %> <%= 'previous' if url_for(:back) == user_calendars_url(current_user) %>"><i class="fa fa-calendar"></i>Calendar</a>
			</div>
		<% end %>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <div class="wrapper">
      <div class="box">
        <div class="row row-offcanvas row-offcanvas-left">
          <%= render 'layouts/sidebar' %>
          <div class="column col-md-10 col-sm-10 col-xs-11" id="main-page">
            <%= render 'layouts/navbar' %>
            <main> 
              <%= yield %>
            </main>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    
		<title>   <%= full_title(yield(:title)) %>    </title>
		<%= stylesheet_link_tag "main", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "main", "data-turbolinks-track" => true %>
		<%#= javascript_include_tag "http://localhost:9292/faye/faye.js" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
		
		<!-- Firebase -->
		<script src="https://cdn.firebase.com/js/client/2.0.2/firebase.js"></script>

		<!-- CodeMirror -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.5.0/codemirror.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/4.5.0/codemirror.css" />

		<!-- Firepad -->
		<link rel="stylesheet" href="https://cdn.firebase.com/libs/firepad/1.1.0/firepad.css" />
		<script src="https://cdn.firebase.com/libs/firepad/1.1.0/firepad.min.js"></script>
		
	</head>

	<body>
		<% if params[:group_id] %>
			<%= render 'popup/popup' %>
		<% end %>
		<div id="sidebar"> <%= render 'layouts/sidebar' %> </div>
		<div id="central-area">
			<div role="navigation" id="navbar"> <%= render 'layouts/navbar' %> </div>
			<main id="central-page">
				<% if @under_construction == true %>
					<div class="first-row">
					</div>
					<div class="main-page">
						<div class="separator"></div>
						<div class="under-construction"></div>
					</div>
				<% elsif @mobile_view == true %>
          <div class="website-not-mobile">no mobile website yet :/</div>
        	<div class="mobile-view"></div>
    		<% else %>
					<%= yield %>
				<% end %>
			</main>
		</div>
	</body>
</html>

app/views/layouts/no_groups.html.erb
NO GROUPS 

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  
  <%= favicon_link_tag 'favicon.ico' %>
  <title>   <%= full_title(yield(:title)) %>    </title>
  <%= stylesheet_link_tag "sessions", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "sessions", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <% if @under_construction == true %>
      <%= render 'layouts/header' %>
      <div class="under-construction"></div>
    <% elsif @mobile_view == true %>
        <div class="website-not-mobile">no mobile website yet :/</div>
        <div class="mobile-view"></div>
    <% else %>
      <%= render 'layouts/header' %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title> <%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag "signin", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "signin", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main> <%= yield %> </main>
  </body>
</html>

app/views/layouts/temp.html.erb
<div id="slide-more-groups" class="slide">
  <div class="slide-container">
    <div class="slide-header">
      <span class="header-title">Groups gestion</span>
      <div class="fa fa-close" id="close-popup"></div> 
    </div>
    <div class="slide-body">

      <!-- NOTIF -->
      <div class="slide-notif"></div>

      <!-- LEFT -->
      <div class="left-container">
        
        <!-- NEW GROUP -->
        <div class="grey-wrapper">
          <div class="new-group-wrapper wrapper-default">
            <span class="new-group-title title-default">Create a new group</span>

            <%= text_field_tag :name, '', class: "input-wrapper", id: "new-group-input" %>
            <div class="submit-default" id="new-group-submit">Create</div>
          </div>
        </div>
        
       <!--  <div class="new-member-wrapper wrapper-default">
          <span class="new-member-title title-default">Add Member</span>

          <%#= text_field_tag :name, '', class: "input-wrapper", id: "new-group-input" %>
          <div class="submit-default" id="new-member-submit">Add</div>
        </div>
 -->
        <div class="new-member-wrapper wrapper-default">
          <span class="new-member-title title-default">Add Member</span>
            <div id="user_search">
              <input class="typeahead" type="text" placeholder="Invite users" name="user[email]">
              <input type="submit" value="Submit">
            </div>
        </div>

        

        <!-- ADD USER -->

       <!--  <div class="wrapper-default", id="list-member-wrapper">
          <span class="title-default" id="list-member-title">Member list</span>
          <div class="member-added">
            <span class="fa fa-user"></span>
            <span class="user-name">Glouffi</span>
            <span class="fa fa-close delete-added-user"></span> 
          </div>
          <div class="member-added">
            <span class="fa fa-user"></span>
            <span class="user-name">Claire</span>
            <span class="fa fa-close delete-added-user"></span> 
          </div>
        </div> -->

        <!-- <div class="new-member">
          <span class="fa fa-user"></span>
          <%= text_field_tag :name, '', class: "user-name-add" %>
        </div> -->
      </div>
      
      <!-- RIGHT -->
      <div id="display-all-groups">
        <% current_groups.each do |group| %>
          <%= link_to user_group_calendar_path(current_user, group, group.calendar), class: "lateral-nav-element" do %>
            <object type="image/svg+xml" data="<%= asset_path 'group-pic.svg' %>" id="profile-pic"></object>
            <span class="group-name-sidebar" group_id="<%= group.id %>"><%= group.name %></span>
          <% end %>
        <% end %>
      </div>

    </div>
    <div class="slide-footer"></div>
  </div>
</div>